### PR TITLE
Rename sensor_manager to loadable_manager

### PR DESCRIPTION
**Pull request by adamgreig**
This pull request also contains all the changes needed elsewhere to ensure that
things keep working and tests keep passing. Notably it changes parser's
fitlering behaviour to remove Parser._normal_filter and replace it with a call
to loadable_manager.run (which has been renamed from .parse).

In addition, filters in flight documents will now have to say 'filter' instead
of 'callable', and the thing they specify will have to point to a filter that
has been loaded by the loadable_manager (i.e., its module is specified in the
configuration file). This makes filters a lot more like sensors for 'normal'
filters, which is nice, and keeps things a bit DRYer.

_Base_ sensors are no longer loaded by default and must be specified in the config file.

Finally, filter functions should now accept (config, data) for their args if
they want a config, rather than (data, config) as before, to ensure they fit in
with sensors. Filters may continue to only specify (data), and sensors may also
now do this if they do not need a config.

### CODE REVIEW

**Comment by adamgreig** [comment]
Before this code is deployed, all existing configuration documents that specify a normal filter via 'callable' will need changing to 'filter'.

**Comment by danielrichman** [comment]
All good!

I've tweaked a few strings: commit is at [loadablemanager 5fc2101].

One thing I noticed:

If a sensor is configured:

```
{"type": "loadable.function", "name": "target stuff", "arbitary stuff": True}
```

then it is called

```
loadable.function({"type": "loadable.function", "name": "target stuff", "arbitary stuff": True}, some_data)
```

i.e., the whole dict. However, if a filter is configured:

```
{"type": "normal", "filter": "loadable.function", "config": {"arbitrary stuff": True}}
```

then it is called

```
loadable.function({"arbitrary stuff": True}, some_data)
```

I think they should both use the same style but I'm not sure which of the two is better. I think I prefer the sensor style since it flattens the flight documents a little bit

We might also be able to make the format and meaning of the keys in the configuration the same: "type" means two different things. Perhaps a sensor should be specified "sensor": "loadable.function".

**Comment by adamgreig** [comment]
Oops, looked like I missed a couple of 'sensor' references. I agree with the change in configuration style, will do that now.

**Comment by adamgreig** [comment]
**New breaking change: all config documents need 'type' replacing with 'sensor' in flight documents** and **filters are now given the entire filter dictionary instead of just the 'config' key** (though the latter shouldn't change anything)

This is in addition to: **filters must say 'filter' and not 'callable'** and **filters now have argument order config,data** (though this has already been fixed for all the habitat filters)

**Comment by danielrichman** [comment]
Oh, I forgot. Should we add habitat.filters to habitat.yml:loadables?

**Comment by adamgreig** [comment]
Yea, definitely. What name? 'filters'? 'common_filters'?

**Comment by danielrichman** [comment]
well if we want to call it common_filters, then we should also call stdtelem and base stdtelem_sensors and base_sensors or sensors_base or what; I'm unsure.

How about sensors.base and sensors.stdtelem and filters.common?
Slightly inconsistent in that the two sensors ones are similar to the modules, habitat.sensors.{base,stdtelem} whereas filters.common would be habitat.filters

**Comment by danielrichman** [comment]
OTOH, just calling it 'common' is fine with me

**Comment by adamgreig** [comment]
I like the idea of keeping the loadables namespace fairly flat for now, so 'common' it is. we can always revisit this.

**Comment by adamgreig** [comment]
wait, though on the other hand it's more consistent to say "filters" seeing as that's where we get the names for base and stdtelem for... just annoying that 'filters' implies it would be all the filters. but then again, custom flights might have a payload name module and mix sensors and filters inside it, like

mypayload.do_fix and mypayload.specialfield and then the loadable'd be "mypayload" I guess?

**Comment by danielrichman** [comment]
so maybe we could merge habitat.sensors and habitat.filters into habitat.core or base or something, and then maybe have
core.{ascii_{int,float},string,simple_map,numeric_scale,semicolons_to_commas} (i.e., sensors.base + filters) and core.stdtelem.{coordinate,time}

**Comment by adamgreig** [comment]
Is 'core' the best word?

I think "sensors.core.ascii_int" or "filters.common.semicolons_to_colons" has too much redundant 'sensors' and 'filters' sitting around, so going for an approach with ideally just one dot would be nice. Equally we could have 'stdtelem' instead of 'core.stdtelem' - it doesn't matter where the library actually is, but for Loadable's point of view we can just call it stdtelem.

Not sure if 'core' is the best top level word to use for all the basic filters and sensors though.

**Comment by danielrichman** [comment]
OK so stdtelem top level is fine because it's clear what's contained in the module. base: not so much.... but I'm unsure what would be better without being too verbose. How about we have:
- stdtelem: habitat.sensors.stdtelem
- basic or simple or types (or just keep it as base? I don't know) (?): habitat.sensors.base
- filters: habitat.filters

... I think that would be ok; even if we've gone in circles

**Comment by adamgreig** [comment]
so to recap IRC, we're actually gonna go for:
- sensors.base: habitat.sensors.base
- sensors.stdtelem: habitat.sensors.stdtelem
- filters.common: habitat.filters

but then the trick is, we also have parser prepend 'filters.' when it looks for filters, and parser modules prepend 'sensors.' when looking for sensors, so the configuration docs can just say 'common.whatever_filter' and 'stdtelem.time' and it'l work! best of both worlds? I think so! equally, because the 'filters.' at the start doesn't actually reflect the real namespace, new modules can be added anywhere:
- sensors.mypayload: habitat_extensions.mypayload.sensors

brace for commit shortly to do this

**Comment by danielrichman** [comment]
Upgrade script for breaking changes: https://gist.github.com/1158331

**Pull request merged**
